# Generated by Django 3.2.4 on 2021-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedurls',
            name='shorten_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
